# most personal metadata can be found in ./resume.json

- description: Portfolio of web &amp; ui designer/developer hybrid Parminder Klair.
  img: ../src/images/twitter-card.png

  availability:
    status: true
    available: '👔 Available for new projects. <a href="mailto:perminder.klair@gmail.com">Let’s talk</a>!'
    unavailable: Not available for new projects.

  # Footer actions
  gpg: https://kretschmann.io/pub.gpg
  addressbook: /perminder-klair.vcf

  typekitID: dtg3zui

  # Analytics tools
  matomoUrl: https://analytics.klair.co
  matomoSite: 2

  allowedHosts:
    - klair.co
    - beta.klair.co
    - localhost
